# check spelling, codestyle
name: Style and Docstring Check

on: [pull_request, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTEST_ADDOPTS: "--color=yes"

jobs:
  docstringcheck:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: "pip"

      - uses: actions/cache@v4
        with:
          path: ~/.local/share/pyvista/examples
          key: Examples-Data-${{ hashFiles('*') }}
          restore-keys: |
            Examples-Data-

      - name: Install pyvista and doctest requirements
        run: |
          pip install -e .[test]

      - uses: awalsh128/cache-apt-pkgs-action@v1.4.3
        with:
          packages: libgl1-mesa-glx xvfb
          version: 3.0

      - name: Software Report
        run: |
          python -c "import pyvista; print(pyvista.Report()); from pyvista import examples; print('Examples path:', examples.USER_DATA_PATH)"
          which python
          pip list

      - name: Test core docstrings
        continue-on-error: true
        run: xvfb-run -s '-maxclients 2048' -a python -m pytest -v --doctest-modules pyvista/core

      - name: Test plotting docstrings
        continue-on-error: true
        run: xvfb-run -s '-maxclients 2048' -a python -m pytest -v --doctest-modules pyvista/plotting --ignore=pyvista/plotting/charts.py

      - name: Test charts docstrings
        continue-on-error: true
        run: xvfb-run -s '-maxclients 2048' -a python -m pytest -v --doctest-modules pyvista/plotting/charts.py

      - name: Test remaining docstrings
        continue-on-error: true
        run: xvfb-run -s '-maxclients 2048' -a python -m pytest -v --doctest-modules pyvista --ignore=pyvista/core --ignore=pyvista/plotting --ignore=pyvista/plotting/charts.py

      - name: Test Package Docstrings with Local Namespace
        run: xvfb-run -s '-maxclients 2048' -a make doctest-modules-local-namespace

  vale:
    name: Vale
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install test dependencies
        run: pip install .[docs]

      # this is equivalent to
      # vale --config doc/.vale.ini doc pyvista examples
      - name: "Run Vale"
        uses: errata-ai/vale-action@reviewdog
        with:
          files: '["doc", "pyvista", "examples"]'
          vale_flags: "--config=doc/.vale.ini"
          reporter: github-pr-check
          level: error
          filter_mode: nofilter
          fail_on_error: true
          version: 2.29.5
          reviewdog_url: https://github.com/reviewdog/reviewdog/releases/download/v0.17.5/reviewdog_0.17.5_Linux_x86_64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
